spring:
  application:
    name: redis-score-system-enhanced
  redis:
    host: localhost # Or the name of your Redis service in docker-compose, e.g., 'redis'
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: score-group-enhanced
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.scoresystem.model"

# Custom properties for Redis Pub/Sub
app:
  redis:
    pubsub-channel: score-updates-pubsub-channel
    leaderboard-key: leaderboard
    user-details-key-prefix: user

server:
  port: 8080